### ISSUE TITLE
Problems with babel-loader and docs

### ISSUE THREAD

**Issue by tur-ing** [reactjs/react-router#3145]
If I try to run the docs, I get the following error:

```
ERROR in multi main
Module not found: Error: Cannot resolve module 'babel-loader' in /Users/Marcel/Development/material-ui/docs
 @ multi main
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 413 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/www/index.html 1.67 kB {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/index.js 411 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
webpack: bundle is now VALID.
```

And if I install babel-loader manually, I get the following error:

```
ERROR in ./src/app/app.jsx
Module build failed: ReferenceError: Unknown plugin "transform-replace-object-assign" specified in "/Users/Marcel/Development/material-ui/docs/src/.babelrc" at 0, attempted to resolve relative to "/Users/Marcel/Development/material-ui/docs/src"
    at /Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:191:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:167:20)
    at OptionManager.mergeOptions (/Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:36)
    at OptionManager.addConfig (/Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:219:10)
    at OptionManager.findConfigs (/Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:425:16)
    at OptionManager.init (/Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:473:12)
    at File.initOptions (/Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/file/index.js:206:75)
    at new File (/Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/file/index.js:124:22)
    at Pipeline.transform (/Users/Marcel/Development/material-ui/docs/node_modules/babel-core/lib/transformation/pipeline.js:44:16)
    at transpile (/Users/Marcel/Development/material-ui/docs/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/Marcel/Development/material-ui/docs/node_modules/babel-loader/index.js:88:12)
 @ multi main
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 413 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/www/index.html 1.67 kB {0} [built]
        [1] ./~/html-webpack-plugin/~/lodash/index.js 411 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
webpack: bundle is now VALID.

```

**Comment by taion** [comment]
I think you filed this against the wrong repo...

**Comment by taion** [comment]
TIL GH has a race condition around closing issues:

![image](https://cloud.githubusercontent.com/assets/3112159/13510000/96681788-e15c-11e5-9e23-049051420f9a.png)

**Comment by timdorr** [comment]
"There are only two hard problems in distributed systems: 2. Exactly-once delivery 1. Guaranteed order of messages 2. Exactly-once delivery"
