### ISSUE TITLE
babel-node cannot transform

### ISSUE THREAD

**Issue by willin** [reactjs/react-router#3403]
## Version
2.3.0

## Test Case

https://github.com/reactjs/react-router-tutorial

## Steps to reproduce

lesson 14

add webpack-hot-middleware

## Expected Behavior

babel-node server

```
SyntaxError: routes.js: Unexpected token (10:2)
   8 |
   9 | module.exports = (
> 10 |   <Route path="/" component={App}>
     |   ^
  11 |     <IndexRoute component={Home}/>
  12 |     <Route path="/repos" component={Repos}>
  13 |       <Route path="/repos/:userName/:repoName" component={Repo}/>
    at Parser.pp.raise (/Users/willin/.nvm/versions/node/v5.10.1/lib/node_modules/babel-cli/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (/Users/willin/.nvm/versions/node/v5.10.1/lib/node_modules/babel-cli/node_modules/babylon/index.js:2817:8)
    at Parser.pp.parseExprAtom (/Users/willin/.nvm/versions/node/v5.10.1/lib/node_modules/babel-cli/node_modules/babylon/index.js:749:12)
    at Parser.pp.parseExprSubscripts (/Users/willin/.nvm/versions/node/v5.10.1/lib/node_modules/babel-cli/node_modules/babylon/index.js:504:
19)
    at Parser.pp.parseMaybeUnary (/Users/willin/.nvm/versions/node/v5.10.1/lib/node_modules/babel-cli/node_modules/babylon/index.js:484:19)
    at Parser.pp.parseExprOps (/Users/willin/.nvm/versions/node/v5.10.1/lib/node_modules/babel-cli/node_modules/babylon/index.js:415:19)
    at Parser.pp.parseMaybeConditional (/Users/willin/.nvm/versions/node/v5.10.1/lib/node_modules/babel-cli/node_modules/babylon/index.js:39

7:19)
```

bundled:

```
chunk    {0} server.bundle.js (main) 73.1 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] ./~/.npminstall/html-entities/1.2.0/html-entities/lib/html5-entities.js 49 kB {0} [built]
    [2] ./~/.npminstall/ansi-html/0.0.5/ansi-html/index.js 4.02 kB {0} [built]
    [3] ./~/.npminstall/ansi-regex/2.0.0/ansi-regex/index.js 135 bytes {0} [built]
    [4] ./~/.npminstall/html-entities/1.2.0/html-entities/index.js 231 bytes {0} [built]
    [5] ./~/.npminstall/html-entities/1.2.0/html-entities/lib/html4-entities.js 6.57 kB {0} [built]
    [6] ./~/.npminstall/html-entities/1.2.0/html-entities/lib/xml-entities.js 2.98 kB {0} [built]

    [7] ./~/.npminstall/strip-ansi/3.0.1/strip-ansi/index.js 161 bytes {0} [built]
    [8] ./~/.npminstall/webpack-hot-middleware/2.10.0/webpack-hot-middleware/client-overlay.js 1.73 kB {0} [built]
    [9] ./~/.npminstall/webpack-hot-middleware/2.10.0/webpack-hot-middleware/client.js 4.18 kB {0} [built]
   [10] ./~/.npminstall/webpack-hot-middleware/2.10.0/webpack-hot-middleware/process-update.js 3.88 kB {0} [built]
   [11] (webpack)/buildin/module.js 251 bytes {0} [built]

ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' 
```

**Comment by taion** [comment]
You need to use the react preset.

**Comment by willin** [comment]
.babelrc

```json
{
  "presets": [
    "es2015-loose",
    "stage-1",
    "react"
  ],
  "plugins": [
    "transform-runtime",
    "transform-react-jsx"
  ]
}
```

**Comment by taion** [comment]
Can you transpile the files normally? This looks like a Babel mis config.
