### ISSUE TITLE
Cannot read property 'removeItem' of undefined - Tests

### ISSUE THREAD

**Issue by BrunoQuaresma** [reactjs/react-router#3790]
I try verify in my test if the browserHistory.push is called when the component did mount.

## Version
2.0.0

## Test Case
https://jsbin.com/vuvotatoza/edit?js,output

## Error
```
Auth section container redirect to panel if has logged user:
     TypeError: Cannot read property 'removeItem' of undefined
      at Object.saveState (node_modules/history/lib/DOMStateStorage.js:26:28)
      at finishTransition (node_modules/history/lib/createBrowserHistory.js:99:22)
      at node_modules/history/lib/createHistory.js:157:13
      at node_modules/history/lib/createHistory.js:133:9
      at next (node_modules/history/lib/AsyncUtils.js:53:7)
      at Object.loopAsync (node_modules/history/lib/AsyncUtils.js:57:3)
      at confirmTransitionTo (node_modules/history/lib/createHistory.js:119:17)
      at transitionTo (node_modules/history/lib/createHistory.js:145:5)
      at Object.push (node_modules/history/lib/createHistory.js:168:5)
      at Object.push (node_modules/history/lib/useBasename.js:105:15)
      at Object.push (node_modules/history/lib/useQueries.js:115:15)
      at Auth.componentDidMount (Auth.jsx:6:20)
      at invokeComponentDidMountWithTimer (node_modules/react/lib/ReactCompositeComponent.js:60:18)
      at CallbackQueue._assign.notifyAll (node_modules/react/lib/CallbackQueue.js:67:22)
      at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (node_modules/react/lib/ReactReconcileTransaction.js:81:26)
      at ReactReconcileTransaction.Mixin.closeAll (node_modules/react/lib/Transaction.js:204:25)
      at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:151:16)
      at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:138:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:98:20)
      at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:285:18)
      at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:371:32)
      at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:392:23)
      at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:85:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:182:26)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Context.<anonymous> (Auth.spec.js:10:21)


```

**Comment by taion** [comment]
Your example doesn't actually run at all.

**Comment by BrunoQuaresma** [comment]
What is missing?

**Comment by taion** [comment]
It's not that it's missing something, it's that it literally doesn't run.

**Comment by BrunoQuaresma** [comment]
It's normal the browserHistory not work in tests and trhow this error?

**Comment by taion** [comment]
The JSBin you provided literally does not run, so I have no idea what error you're talking about.

**Comment by BrunoQuaresma** [comment]
Ahhh ok. But how can i put dependencies like mocha and chai in JSBin?

**Comment by hakunin** [comment]
I bumped into this issue as well and swapping the router history for a memory one resolved this issue.

**Comment by BrunoQuaresma** [comment]
@hakunin Nice. I will try, thanks.
